// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ftpReq.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_ftpReq_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_ftpReq_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3011000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3011002 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/generated_enum_reflection.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_ftpReq_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_ftpReq_2eproto {
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTableField entries[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::AuxillaryParseTableField aux[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTable schema[3]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::FieldMetadata field_metadata[];
  static const ::PROTOBUF_NAMESPACE_ID::internal::SerializationTable serialization_table[];
  static const ::PROTOBUF_NAMESPACE_ID::uint32 offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_ftpReq_2eproto;
namespace protos {
class FtpFileInfo;
class FtpFileInfoDefaultTypeInternal;
extern FtpFileInfoDefaultTypeInternal _FtpFileInfo_default_instance_;
class FtpReq;
class FtpReqDefaultTypeInternal;
extern FtpReqDefaultTypeInternal _FtpReq_default_instance_;
class FtpUserInfo;
class FtpUserInfoDefaultTypeInternal;
extern FtpUserInfoDefaultTypeInternal _FtpUserInfo_default_instance_;
}  // namespace protos
PROTOBUF_NAMESPACE_OPEN
template<> ::protos::FtpFileInfo* Arena::CreateMaybeMessage<::protos::FtpFileInfo>(Arena*);
template<> ::protos::FtpReq* Arena::CreateMaybeMessage<::protos::FtpReq>(Arena*);
template<> ::protos::FtpUserInfo* Arena::CreateMaybeMessage<::protos::FtpUserInfo>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace protos {

enum FtpReq_Type : int {
  FtpReq_Type_DOWNLOAD = 0,
  FtpReq_Type_UPLOAD = 1,
  FtpReq_Type_FtpReq_Type_INT_MIN_SENTINEL_DO_NOT_USE_ = std::numeric_limits<::PROTOBUF_NAMESPACE_ID::int32>::min(),
  FtpReq_Type_FtpReq_Type_INT_MAX_SENTINEL_DO_NOT_USE_ = std::numeric_limits<::PROTOBUF_NAMESPACE_ID::int32>::max()
};
bool FtpReq_Type_IsValid(int value);
constexpr FtpReq_Type FtpReq_Type_Type_MIN = FtpReq_Type_DOWNLOAD;
constexpr FtpReq_Type FtpReq_Type_Type_MAX = FtpReq_Type_UPLOAD;
constexpr int FtpReq_Type_Type_ARRAYSIZE = FtpReq_Type_Type_MAX + 1;

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* FtpReq_Type_descriptor();
template<typename T>
inline const std::string& FtpReq_Type_Name(T enum_t_value) {
  static_assert(::std::is_same<T, FtpReq_Type>::value ||
    ::std::is_integral<T>::value,
    "Incorrect type passed to function FtpReq_Type_Name.");
  return ::PROTOBUF_NAMESPACE_ID::internal::NameOfEnum(
    FtpReq_Type_descriptor(), enum_t_value);
}
inline bool FtpReq_Type_Parse(
    const std::string& name, FtpReq_Type* value) {
  return ::PROTOBUF_NAMESPACE_ID::internal::ParseNamedEnum<FtpReq_Type>(
    FtpReq_Type_descriptor(), name, value);
}
// ===================================================================

class FtpUserInfo :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:protos.FtpUserInfo) */ {
 public:
  FtpUserInfo();
  virtual ~FtpUserInfo();

  FtpUserInfo(const FtpUserInfo& from);
  FtpUserInfo(FtpUserInfo&& from) noexcept
    : FtpUserInfo() {
    *this = ::std::move(from);
  }

  inline FtpUserInfo& operator=(const FtpUserInfo& from) {
    CopyFrom(from);
    return *this;
  }
  inline FtpUserInfo& operator=(FtpUserInfo&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const FtpUserInfo& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const FtpUserInfo* internal_default_instance() {
    return reinterpret_cast<const FtpUserInfo*>(
               &_FtpUserInfo_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(FtpUserInfo& a, FtpUserInfo& b) {
    a.Swap(&b);
  }
  inline void Swap(FtpUserInfo* other) {
    if (other == this) return;
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline FtpUserInfo* New() const final {
    return CreateMaybeMessage<FtpUserInfo>(nullptr);
  }

  FtpUserInfo* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<FtpUserInfo>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const FtpUserInfo& from);
  void MergeFrom(const FtpUserInfo& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(FtpUserInfo* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "protos.FtpUserInfo";
  }
  private:
  inline ::PROTOBUF_NAMESPACE_ID::Arena* GetArenaNoVirtual() const {
    return nullptr;
  }
  inline void* MaybeArenaPtr() const {
    return nullptr;
  }
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_ftpReq_2eproto);
    return ::descriptor_table_ftpReq_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kNameFieldNumber = 1,
  };
  // string name = 1;
  void clear_name();
  const std::string& name() const;
  void set_name(const std::string& value);
  void set_name(std::string&& value);
  void set_name(const char* value);
  void set_name(const char* value, size_t size);
  std::string* mutable_name();
  std::string* release_name();
  void set_allocated_name(std::string* name);
  private:
  const std::string& _internal_name() const;
  void _internal_set_name(const std::string& value);
  std::string* _internal_mutable_name();
  public:

  // @@protoc_insertion_point(class_scope:protos.FtpUserInfo)
 private:
  class _Internal;

  ::PROTOBUF_NAMESPACE_ID::internal::InternalMetadataWithArena _internal_metadata_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr name_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_ftpReq_2eproto;
};
// -------------------------------------------------------------------

class FtpFileInfo :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:protos.FtpFileInfo) */ {
 public:
  FtpFileInfo();
  virtual ~FtpFileInfo();

  FtpFileInfo(const FtpFileInfo& from);
  FtpFileInfo(FtpFileInfo&& from) noexcept
    : FtpFileInfo() {
    *this = ::std::move(from);
  }

  inline FtpFileInfo& operator=(const FtpFileInfo& from) {
    CopyFrom(from);
    return *this;
  }
  inline FtpFileInfo& operator=(FtpFileInfo&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const FtpFileInfo& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const FtpFileInfo* internal_default_instance() {
    return reinterpret_cast<const FtpFileInfo*>(
               &_FtpFileInfo_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(FtpFileInfo& a, FtpFileInfo& b) {
    a.Swap(&b);
  }
  inline void Swap(FtpFileInfo* other) {
    if (other == this) return;
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline FtpFileInfo* New() const final {
    return CreateMaybeMessage<FtpFileInfo>(nullptr);
  }

  FtpFileInfo* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<FtpFileInfo>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const FtpFileInfo& from);
  void MergeFrom(const FtpFileInfo& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(FtpFileInfo* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "protos.FtpFileInfo";
  }
  private:
  inline ::PROTOBUF_NAMESPACE_ID::Arena* GetArenaNoVirtual() const {
    return nullptr;
  }
  inline void* MaybeArenaPtr() const {
    return nullptr;
  }
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_ftpReq_2eproto);
    return ::descriptor_table_ftpReq_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kNameFieldNumber = 1,
    kPathFieldNumber = 2,
    kFidFieldNumber = 3,
    kSizeFieldNumber = 4,
  };
  // string name = 1;
  void clear_name();
  const std::string& name() const;
  void set_name(const std::string& value);
  void set_name(std::string&& value);
  void set_name(const char* value);
  void set_name(const char* value, size_t size);
  std::string* mutable_name();
  std::string* release_name();
  void set_allocated_name(std::string* name);
  private:
  const std::string& _internal_name() const;
  void _internal_set_name(const std::string& value);
  std::string* _internal_mutable_name();
  public:

  // string path = 2;
  void clear_path();
  const std::string& path() const;
  void set_path(const std::string& value);
  void set_path(std::string&& value);
  void set_path(const char* value);
  void set_path(const char* value, size_t size);
  std::string* mutable_path();
  std::string* release_path();
  void set_allocated_path(std::string* path);
  private:
  const std::string& _internal_path() const;
  void _internal_set_path(const std::string& value);
  std::string* _internal_mutable_path();
  public:

  // uint32 fid = 3;
  void clear_fid();
  ::PROTOBUF_NAMESPACE_ID::uint32 fid() const;
  void set_fid(::PROTOBUF_NAMESPACE_ID::uint32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::uint32 _internal_fid() const;
  void _internal_set_fid(::PROTOBUF_NAMESPACE_ID::uint32 value);
  public:

  // uint32 size = 4;
  void clear_size();
  ::PROTOBUF_NAMESPACE_ID::uint32 size() const;
  void set_size(::PROTOBUF_NAMESPACE_ID::uint32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::uint32 _internal_size() const;
  void _internal_set_size(::PROTOBUF_NAMESPACE_ID::uint32 value);
  public:

  // @@protoc_insertion_point(class_scope:protos.FtpFileInfo)
 private:
  class _Internal;

  ::PROTOBUF_NAMESPACE_ID::internal::InternalMetadataWithArena _internal_metadata_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr name_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr path_;
  ::PROTOBUF_NAMESPACE_ID::uint32 fid_;
  ::PROTOBUF_NAMESPACE_ID::uint32 size_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_ftpReq_2eproto;
};
// -------------------------------------------------------------------

class FtpReq :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:protos.FtpReq) */ {
 public:
  FtpReq();
  virtual ~FtpReq();

  FtpReq(const FtpReq& from);
  FtpReq(FtpReq&& from) noexcept
    : FtpReq() {
    *this = ::std::move(from);
  }

  inline FtpReq& operator=(const FtpReq& from) {
    CopyFrom(from);
    return *this;
  }
  inline FtpReq& operator=(FtpReq&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const FtpReq& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const FtpReq* internal_default_instance() {
    return reinterpret_cast<const FtpReq*>(
               &_FtpReq_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    2;

  friend void swap(FtpReq& a, FtpReq& b) {
    a.Swap(&b);
  }
  inline void Swap(FtpReq* other) {
    if (other == this) return;
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline FtpReq* New() const final {
    return CreateMaybeMessage<FtpReq>(nullptr);
  }

  FtpReq* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<FtpReq>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const FtpReq& from);
  void MergeFrom(const FtpReq& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(FtpReq* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "protos.FtpReq";
  }
  private:
  inline ::PROTOBUF_NAMESPACE_ID::Arena* GetArenaNoVirtual() const {
    return nullptr;
  }
  inline void* MaybeArenaPtr() const {
    return nullptr;
  }
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_ftpReq_2eproto);
    return ::descriptor_table_ftpReq_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  typedef FtpReq_Type Type;
  static constexpr Type DOWNLOAD =
    FtpReq_Type_DOWNLOAD;
  static constexpr Type UPLOAD =
    FtpReq_Type_UPLOAD;
  static inline bool Type_IsValid(int value) {
    return FtpReq_Type_IsValid(value);
  }
  static constexpr Type Type_MIN =
    FtpReq_Type_Type_MIN;
  static constexpr Type Type_MAX =
    FtpReq_Type_Type_MAX;
  static constexpr int Type_ARRAYSIZE =
    FtpReq_Type_Type_ARRAYSIZE;
  static inline const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor*
  Type_descriptor() {
    return FtpReq_Type_descriptor();
  }
  template<typename T>
  static inline const std::string& Type_Name(T enum_t_value) {
    static_assert(::std::is_same<T, Type>::value ||
      ::std::is_integral<T>::value,
      "Incorrect type passed to function Type_Name.");
    return FtpReq_Type_Name(enum_t_value);
  }
  static inline bool Type_Parse(const std::string& name,
      Type* value) {
    return FtpReq_Type_Parse(name, value);
  }

  // accessors -------------------------------------------------------

  enum : int {
    kKeyFieldNumber = 3,
    kUserInfoFieldNumber = 1,
    kFileInfoFieldNumber = 2,
  };
  // string key = 3;
  void clear_key();
  const std::string& key() const;
  void set_key(const std::string& value);
  void set_key(std::string&& value);
  void set_key(const char* value);
  void set_key(const char* value, size_t size);
  std::string* mutable_key();
  std::string* release_key();
  void set_allocated_key(std::string* key);
  private:
  const std::string& _internal_key() const;
  void _internal_set_key(const std::string& value);
  std::string* _internal_mutable_key();
  public:

  // .protos.FtpUserInfo userInfo = 1;
  bool has_userinfo() const;
  private:
  bool _internal_has_userinfo() const;
  public:
  void clear_userinfo();
  const ::protos::FtpUserInfo& userinfo() const;
  ::protos::FtpUserInfo* release_userinfo();
  ::protos::FtpUserInfo* mutable_userinfo();
  void set_allocated_userinfo(::protos::FtpUserInfo* userinfo);
  private:
  const ::protos::FtpUserInfo& _internal_userinfo() const;
  ::protos::FtpUserInfo* _internal_mutable_userinfo();
  public:

  // .protos.FtpFileInfo fileInfo = 2;
  bool has_fileinfo() const;
  private:
  bool _internal_has_fileinfo() const;
  public:
  void clear_fileinfo();
  const ::protos::FtpFileInfo& fileinfo() const;
  ::protos::FtpFileInfo* release_fileinfo();
  ::protos::FtpFileInfo* mutable_fileinfo();
  void set_allocated_fileinfo(::protos::FtpFileInfo* fileinfo);
  private:
  const ::protos::FtpFileInfo& _internal_fileinfo() const;
  ::protos::FtpFileInfo* _internal_mutable_fileinfo();
  public:

  // @@protoc_insertion_point(class_scope:protos.FtpReq)
 private:
  class _Internal;

  ::PROTOBUF_NAMESPACE_ID::internal::InternalMetadataWithArena _internal_metadata_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr key_;
  ::protos::FtpUserInfo* userinfo_;
  ::protos::FtpFileInfo* fileinfo_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_ftpReq_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// FtpUserInfo

// string name = 1;
inline void FtpUserInfo::clear_name() {
  name_.ClearToEmptyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline const std::string& FtpUserInfo::name() const {
  // @@protoc_insertion_point(field_get:protos.FtpUserInfo.name)
  return _internal_name();
}
inline void FtpUserInfo::set_name(const std::string& value) {
  _internal_set_name(value);
  // @@protoc_insertion_point(field_set:protos.FtpUserInfo.name)
}
inline std::string* FtpUserInfo::mutable_name() {
  // @@protoc_insertion_point(field_mutable:protos.FtpUserInfo.name)
  return _internal_mutable_name();
}
inline const std::string& FtpUserInfo::_internal_name() const {
  return name_.GetNoArena();
}
inline void FtpUserInfo::_internal_set_name(const std::string& value) {
  
  name_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value);
}
inline void FtpUserInfo::set_name(std::string&& value) {
  
  name_.SetNoArena(
    &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:protos.FtpUserInfo.name)
}
inline void FtpUserInfo::set_name(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  name_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:protos.FtpUserInfo.name)
}
inline void FtpUserInfo::set_name(const char* value, size_t size) {
  
  name_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:protos.FtpUserInfo.name)
}
inline std::string* FtpUserInfo::_internal_mutable_name() {
  
  return name_.MutableNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline std::string* FtpUserInfo::release_name() {
  // @@protoc_insertion_point(field_release:protos.FtpUserInfo.name)
  
  return name_.ReleaseNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline void FtpUserInfo::set_allocated_name(std::string* name) {
  if (name != nullptr) {
    
  } else {
    
  }
  name_.SetAllocatedNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), name);
  // @@protoc_insertion_point(field_set_allocated:protos.FtpUserInfo.name)
}

// -------------------------------------------------------------------

// FtpFileInfo

// string name = 1;
inline void FtpFileInfo::clear_name() {
  name_.ClearToEmptyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline const std::string& FtpFileInfo::name() const {
  // @@protoc_insertion_point(field_get:protos.FtpFileInfo.name)
  return _internal_name();
}
inline void FtpFileInfo::set_name(const std::string& value) {
  _internal_set_name(value);
  // @@protoc_insertion_point(field_set:protos.FtpFileInfo.name)
}
inline std::string* FtpFileInfo::mutable_name() {
  // @@protoc_insertion_point(field_mutable:protos.FtpFileInfo.name)
  return _internal_mutable_name();
}
inline const std::string& FtpFileInfo::_internal_name() const {
  return name_.GetNoArena();
}
inline void FtpFileInfo::_internal_set_name(const std::string& value) {
  
  name_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value);
}
inline void FtpFileInfo::set_name(std::string&& value) {
  
  name_.SetNoArena(
    &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:protos.FtpFileInfo.name)
}
inline void FtpFileInfo::set_name(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  name_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:protos.FtpFileInfo.name)
}
inline void FtpFileInfo::set_name(const char* value, size_t size) {
  
  name_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:protos.FtpFileInfo.name)
}
inline std::string* FtpFileInfo::_internal_mutable_name() {
  
  return name_.MutableNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline std::string* FtpFileInfo::release_name() {
  // @@protoc_insertion_point(field_release:protos.FtpFileInfo.name)
  
  return name_.ReleaseNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline void FtpFileInfo::set_allocated_name(std::string* name) {
  if (name != nullptr) {
    
  } else {
    
  }
  name_.SetAllocatedNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), name);
  // @@protoc_insertion_point(field_set_allocated:protos.FtpFileInfo.name)
}

// string path = 2;
inline void FtpFileInfo::clear_path() {
  path_.ClearToEmptyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline const std::string& FtpFileInfo::path() const {
  // @@protoc_insertion_point(field_get:protos.FtpFileInfo.path)
  return _internal_path();
}
inline void FtpFileInfo::set_path(const std::string& value) {
  _internal_set_path(value);
  // @@protoc_insertion_point(field_set:protos.FtpFileInfo.path)
}
inline std::string* FtpFileInfo::mutable_path() {
  // @@protoc_insertion_point(field_mutable:protos.FtpFileInfo.path)
  return _internal_mutable_path();
}
inline const std::string& FtpFileInfo::_internal_path() const {
  return path_.GetNoArena();
}
inline void FtpFileInfo::_internal_set_path(const std::string& value) {
  
  path_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value);
}
inline void FtpFileInfo::set_path(std::string&& value) {
  
  path_.SetNoArena(
    &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:protos.FtpFileInfo.path)
}
inline void FtpFileInfo::set_path(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  path_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:protos.FtpFileInfo.path)
}
inline void FtpFileInfo::set_path(const char* value, size_t size) {
  
  path_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:protos.FtpFileInfo.path)
}
inline std::string* FtpFileInfo::_internal_mutable_path() {
  
  return path_.MutableNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline std::string* FtpFileInfo::release_path() {
  // @@protoc_insertion_point(field_release:protos.FtpFileInfo.path)
  
  return path_.ReleaseNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline void FtpFileInfo::set_allocated_path(std::string* path) {
  if (path != nullptr) {
    
  } else {
    
  }
  path_.SetAllocatedNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), path);
  // @@protoc_insertion_point(field_set_allocated:protos.FtpFileInfo.path)
}

// uint32 fid = 3;
inline void FtpFileInfo::clear_fid() {
  fid_ = 0u;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 FtpFileInfo::_internal_fid() const {
  return fid_;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 FtpFileInfo::fid() const {
  // @@protoc_insertion_point(field_get:protos.FtpFileInfo.fid)
  return _internal_fid();
}
inline void FtpFileInfo::_internal_set_fid(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  
  fid_ = value;
}
inline void FtpFileInfo::set_fid(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  _internal_set_fid(value);
  // @@protoc_insertion_point(field_set:protos.FtpFileInfo.fid)
}

// uint32 size = 4;
inline void FtpFileInfo::clear_size() {
  size_ = 0u;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 FtpFileInfo::_internal_size() const {
  return size_;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 FtpFileInfo::size() const {
  // @@protoc_insertion_point(field_get:protos.FtpFileInfo.size)
  return _internal_size();
}
inline void FtpFileInfo::_internal_set_size(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  
  size_ = value;
}
inline void FtpFileInfo::set_size(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  _internal_set_size(value);
  // @@protoc_insertion_point(field_set:protos.FtpFileInfo.size)
}

// -------------------------------------------------------------------

// FtpReq

// .protos.FtpUserInfo userInfo = 1;
inline bool FtpReq::_internal_has_userinfo() const {
  return this != internal_default_instance() && userinfo_ != nullptr;
}
inline bool FtpReq::has_userinfo() const {
  return _internal_has_userinfo();
}
inline void FtpReq::clear_userinfo() {
  if (GetArenaNoVirtual() == nullptr && userinfo_ != nullptr) {
    delete userinfo_;
  }
  userinfo_ = nullptr;
}
inline const ::protos::FtpUserInfo& FtpReq::_internal_userinfo() const {
  const ::protos::FtpUserInfo* p = userinfo_;
  return p != nullptr ? *p : *reinterpret_cast<const ::protos::FtpUserInfo*>(
      &::protos::_FtpUserInfo_default_instance_);
}
inline const ::protos::FtpUserInfo& FtpReq::userinfo() const {
  // @@protoc_insertion_point(field_get:protos.FtpReq.userInfo)
  return _internal_userinfo();
}
inline ::protos::FtpUserInfo* FtpReq::release_userinfo() {
  // @@protoc_insertion_point(field_release:protos.FtpReq.userInfo)
  
  ::protos::FtpUserInfo* temp = userinfo_;
  userinfo_ = nullptr;
  return temp;
}
inline ::protos::FtpUserInfo* FtpReq::_internal_mutable_userinfo() {
  
  if (userinfo_ == nullptr) {
    auto* p = CreateMaybeMessage<::protos::FtpUserInfo>(GetArenaNoVirtual());
    userinfo_ = p;
  }
  return userinfo_;
}
inline ::protos::FtpUserInfo* FtpReq::mutable_userinfo() {
  // @@protoc_insertion_point(field_mutable:protos.FtpReq.userInfo)
  return _internal_mutable_userinfo();
}
inline void FtpReq::set_allocated_userinfo(::protos::FtpUserInfo* userinfo) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaNoVirtual();
  if (message_arena == nullptr) {
    delete userinfo_;
  }
  if (userinfo) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena = nullptr;
    if (message_arena != submessage_arena) {
      userinfo = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, userinfo, submessage_arena);
    }
    
  } else {
    
  }
  userinfo_ = userinfo;
  // @@protoc_insertion_point(field_set_allocated:protos.FtpReq.userInfo)
}

// .protos.FtpFileInfo fileInfo = 2;
inline bool FtpReq::_internal_has_fileinfo() const {
  return this != internal_default_instance() && fileinfo_ != nullptr;
}
inline bool FtpReq::has_fileinfo() const {
  return _internal_has_fileinfo();
}
inline void FtpReq::clear_fileinfo() {
  if (GetArenaNoVirtual() == nullptr && fileinfo_ != nullptr) {
    delete fileinfo_;
  }
  fileinfo_ = nullptr;
}
inline const ::protos::FtpFileInfo& FtpReq::_internal_fileinfo() const {
  const ::protos::FtpFileInfo* p = fileinfo_;
  return p != nullptr ? *p : *reinterpret_cast<const ::protos::FtpFileInfo*>(
      &::protos::_FtpFileInfo_default_instance_);
}
inline const ::protos::FtpFileInfo& FtpReq::fileinfo() const {
  // @@protoc_insertion_point(field_get:protos.FtpReq.fileInfo)
  return _internal_fileinfo();
}
inline ::protos::FtpFileInfo* FtpReq::release_fileinfo() {
  // @@protoc_insertion_point(field_release:protos.FtpReq.fileInfo)
  
  ::protos::FtpFileInfo* temp = fileinfo_;
  fileinfo_ = nullptr;
  return temp;
}
inline ::protos::FtpFileInfo* FtpReq::_internal_mutable_fileinfo() {
  
  if (fileinfo_ == nullptr) {
    auto* p = CreateMaybeMessage<::protos::FtpFileInfo>(GetArenaNoVirtual());
    fileinfo_ = p;
  }
  return fileinfo_;
}
inline ::protos::FtpFileInfo* FtpReq::mutable_fileinfo() {
  // @@protoc_insertion_point(field_mutable:protos.FtpReq.fileInfo)
  return _internal_mutable_fileinfo();
}
inline void FtpReq::set_allocated_fileinfo(::protos::FtpFileInfo* fileinfo) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaNoVirtual();
  if (message_arena == nullptr) {
    delete fileinfo_;
  }
  if (fileinfo) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena = nullptr;
    if (message_arena != submessage_arena) {
      fileinfo = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, fileinfo, submessage_arena);
    }
    
  } else {
    
  }
  fileinfo_ = fileinfo;
  // @@protoc_insertion_point(field_set_allocated:protos.FtpReq.fileInfo)
}

// string key = 3;
inline void FtpReq::clear_key() {
  key_.ClearToEmptyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline const std::string& FtpReq::key() const {
  // @@protoc_insertion_point(field_get:protos.FtpReq.key)
  return _internal_key();
}
inline void FtpReq::set_key(const std::string& value) {
  _internal_set_key(value);
  // @@protoc_insertion_point(field_set:protos.FtpReq.key)
}
inline std::string* FtpReq::mutable_key() {
  // @@protoc_insertion_point(field_mutable:protos.FtpReq.key)
  return _internal_mutable_key();
}
inline const std::string& FtpReq::_internal_key() const {
  return key_.GetNoArena();
}
inline void FtpReq::_internal_set_key(const std::string& value) {
  
  key_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value);
}
inline void FtpReq::set_key(std::string&& value) {
  
  key_.SetNoArena(
    &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:protos.FtpReq.key)
}
inline void FtpReq::set_key(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  key_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:protos.FtpReq.key)
}
inline void FtpReq::set_key(const char* value, size_t size) {
  
  key_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:protos.FtpReq.key)
}
inline std::string* FtpReq::_internal_mutable_key() {
  
  return key_.MutableNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline std::string* FtpReq::release_key() {
  // @@protoc_insertion_point(field_release:protos.FtpReq.key)
  
  return key_.ReleaseNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline void FtpReq::set_allocated_key(std::string* key) {
  if (key != nullptr) {
    
  } else {
    
  }
  key_.SetAllocatedNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), key);
  // @@protoc_insertion_point(field_set_allocated:protos.FtpReq.key)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace protos

PROTOBUF_NAMESPACE_OPEN

template <> struct is_proto_enum< ::protos::FtpReq_Type> : ::std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::protos::FtpReq_Type>() {
  return ::protos::FtpReq_Type_descriptor();
}

PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_ftpReq_2eproto
